/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const SET_PASSWORD = "SET_PASSWORD";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const RESET_PASSWORD_CONFIRM = 'RESET_PASSWORD_CONFIRM';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAILED = 'RESET_PASSWORD_CONFIRM_FAILED';

export const CHECK_PASSWORD_STATUS = 'CHECK_PASSWORD_STATUS';

/* MENU */
export const SET_MAIN_MENU_CLASSNAME = "SET_MAIN_MENU_CLASSNAME";
export const SET_SUB_MENU_CLASSNAME = "SET_SUB_MENU_CLASSNAME";
export const SET_MENU_NAME = "SET_MENU_NAME";

/* SURVEY */
export const PAGE_LIST = "PAGE_LIST";
export const PAGE_LIST_SUCCESS = "PAGE_LIST_SUCCESS";
export const SELECT_PAGE = "SELECT_PAGE";
export const CONTINUE_SURVEY = "CONTINUE_SURVEY";
export const INPUT_ANSWER = "INPUT_ANSWER";
export const SUBMIT_SURVEY = "SUBMIT_SURVEY";
export const SUBMIT_SURVEY_SUCCESS = "SUBMIT_SURVEY_SUCCESS";
export const ABOUTME = "ABOUTME";
export const SUBMIT_ABOUTME = "SUBMIT_ABOUTME";
export const CLEAR_ABOUTME = "CLEAR_ABOUTME";

/* Notification */
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";

/* Common */
export const TEAM_LIST = "TEAM_LIST";
export const SET_TEAM_LIST = "SET_TEAM_LIST";
export const TEAM_LIST_SUCCESS = "TEAM_LIST_SUCCESS";

export const ORGANIZATION_LIST = "ORGANIZATION_LIST";
export const ORGANIZATION_LIST_SUCCESS = "ORGANIZATION_LIST_SUCCESS";

export const SHGROUP_LIST = "SHGROUP_LIST";
export const SHGROUP_LIST_SUCCESS = "SHGROUP_LIST_SUCCESS";

export const OPTION_LIST = "OPTION_LIST";
export const OPTION_LIST_SUCCESS = "OPTION_LIST_SUCCESS";

export const DRIVER_LIST = "DRIVER_LIST";
export const DRIVER_LIST_SUCCESS = "DRIVER_LIST_SUCCESS";

export const SKIP_QUESTION_LIST = "SKIP_QUESTION_LIST";
export const SKIP_QUESTION_LIST_SUCCESS = "SKIP_QUESTION_LIST_SUCCESS";

export const SHCATEGORY_LIST = "SHCATEGORY_LIST";
export const SHCATEGORY_LIST_SUCCESS = "SHCATEGORY_LIST_SUCCESS";

export const STAKEHOLDER_LIST = "STAKEHOLDER_LIST";
export const STAKEHOLDER_LIST_SUCCESS = "STAKEHOLDER_LIST_SUCCESS";

export const STAKEHOLDER_ANSWER = "STAKEHOLDER_ANSWER";

export const ADD_STAKEHOLDER = "ADD_STAKEHOLDER";
export const ADD_STAKEHOLDER_SUCCESS = "ADD_STAKEHOLDER_SUCCESS";
export const UPDATE_STAKEHOLDER = "UPDATE_STAKEHOLDER";
export const UPDATE_STAKEHOLDER_SUCCESS = "UPDATE_STAKEHOLDER_SUCCESS";

export const UPDATE_STAKEHOLDER_CATEGORY = "UPDATE_STAKEHOLDER_CATEGORY";

export const CLEAR_COMMON = "CLEAR_COMMON";

/* Map */
export const USER_LIST = "USER_LIST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";

export const PROJECT_USER_LIST = "PROJECT_USER_LIST";
export const PROJECT_USER_LIST_SUCCESS = "PROJECT_USER_LIST_SUCCESS";

export const KMAP_DATA = "MAP_DATA";
export const KMAP_DATA_SUCCESS = "KMAP_DATA_SUCCESS";

export const KMAP_SAVE = "KMAP_SAVE";
export const KMAP_SAVE_SUCCESS = "KMAP_SAVE_SUCCESS";

export const PROJECTMAP_DATA = "PROJECTMAP_DATA";
export const PROJECTMAP_DATA_SUCCESS = "PROJECTMAP_DATA_SUCCESS";

export const PROJECTMAP_SAVE = "PROJECTMAP_SAVE";
export const PROJECTMAP_SAVE_SUCCESS = "PROJECTMAP_SAVE_SUCCESS";

export const CLEAR_MAP = "CLEAR_MAP";

/* About Other Question */
export const AOQUESTION_LIST = "AOQUESTION_LIST";
export const AOQUESTION_LIST_SUCCESS = "AOQUESTION_LIST_SUCCESS";
export const SUBMIT_AOQUESTION = "SUBMIT_AOQUESTION";
export const SUBMIT_AOQUESTION_SUCCESS = "SUBMIT_AOQUESTION_SUCCESS";

/* Setting */
export const PROJECT_LIST_BY_USER = "PROJECT_LIST_BY_USER";
export const PROJECT_LIST_BY_USER_SUCCESS = "PROJECT_LIST_BY_USER_SUCCESS";
export const PROJECT_ID = "PROJECT_ID";
export const PROJECT_ID_SUCCESS = "PROJECT_ID_SUCCESS";

export const SURVEY_LIST_BY_PROJECT = "SURVEY_LIST_BY_PROJECT";
export const SURVEY_LIST_BY_PROJECT_SUCCESS = "SURVEY_LIST_BY_PROJECT_SUCCESS";
export const SURVEY_ID = "SURVEY_ID";
export const SURVEY_ID_SUCCESS = "SURVEY_ID_SUCCESS";

/* Add New Topic */
export const ADD_ABOUT_ME_TOPIC = "ADD_ABOUT_ME_TOPIC";
export const ADD_ABOUT_ME_TOPIC_SUCCESS = "ADD_ABOUT_ME_TOPIC_SUCCESS";

export const DELETE_ABOUT_ME_TOPIC = "DELETE_ABOUT_ME_TOPIC";
export const DELETE_ABOUT_ME_TOPIC_SUCCESS = "DELETE_ABOUT_ME_TOPIC_SUCCESS";

export const UPDATE_ABOUT_ME_TOPIC = "UPDATE_ABOUT_ME_TOPIC";
export const UPDATE_ABOUT_ME_TOPIC_SUCCESS = "UPDATE_ABOUT_ME_TOPIC_SUCCESS";

export const ADD_ABOUT_OTHER_TOPIC = "ADD_ABOUT_OTHER_TOPIC";
export const ADD_ABOUT_OTHER_TOPIC_SUCCESS = "ADD_ABOUT_OTHER_TOPIC_SUCCESS";

/* Account */
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const CHANGE_AVATAR = "CHANGE_AVATAR";
export const UPDATE_GUIDE_STATUS = "GUIDE_SHOW_STATUS";
export const UPDATE_GUIDE_STATUS_SUCCESS = "UPDATE_GUIDE_STATUS_SUCCESS";

/* ToolTip Tour */
export const NIKEL_TOUR_CONTENT = "NIKEL_TOUR_CONTENT";
export const NIKEL_TOUR_CONTENT_SUCCESS = "NIKEL_TOUR_CONTENT_SUCCESS";
export const TOOLTIP_TOUR_CONTENT = "TOOLTIP_TOUR_CONTENT";
export const TOOLTIP_TOUR_CONTENT_SUCCESS = "TOOLTIP_TOUR_CONTENT_SUCCESS";
export const PAGE_CONTENT = "PAGE_CONTENT";
export const PAGE_CONTENT_SUCCESS = "PAGE_CONTENT_SUCCESS";

/* Report */
export const REPORT_OVERALL_SENTIMENT = "REPORT_OVERALL_SENTIMENT";
export const REPORT_TOP_POSITIVE_NEGATIVE = "REPORT_TOP_POSITIVE_NEGATIVE";
export const REPORT_FEEDBACK_SUMMARY = "REPORT_FEEDBACK_SUMMARY";
export const REPORT_PARTICIPATION = "REPORT_PARTICIPATION";
export const REPORT_ENGAGEMENT_TREND = "REPORT_ENGAGEMENT_TREND";
export const REPORT_WORDCLOUD = "REPORT_WORDCLOUD";
export const REPORT_SENTIMENT = "REPORT_SENTIMENT";
export const REPORT_PERCEPTION_REALITY = "REPORT_PERCEPTION_REALITY";
export const REPORT_BUBBLECHART = "REPORT_BUBBLECHART";
export const REPORT_MY_MATRIX = "REPORT_MY_MATRIX";
export const REPORT_PROJECT_MATRIX = "REPORT_PROJECT_MATRIX";
export const REPORT_TEXT_VALUE = "REPORT_TEXT_VALUE";
export const REPORT_GET_ACKNOWLEDGEMENT = "REPORT_GET_ACKNOWLEDGEMENT";
export const REPORT_SET_ACKNOWLEDGEMENT = "REPORT_SET_ACKNOWLEDGEMENT";
export const REPORT_VOTE_KEYTHEME = "REPORT_VOTE_KEYTHEME";
export const REPORT_AMQUESTIONCNT = "REPORT_AMQUESTIONCNT";
export const REPORT_ADVISOR = "REPORT_ADVISOR";
export const REPORT_CHECK_DASHBOARD = "REPORT_CHECK_DASHBOARD";
export const REPORT_DRIVER_ANALYSIS_CNT = "REPORT_DRIVER_ANALYSIS_CNT";
export const REPORT_KEYTHEME_MENU_CNT = "REPORT_KEYTHEME_MENU_CNT";

/* Admin */
export const ADMIN_USER_LIST = "ADMIN_USER_LIST"
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS"
export const ADMIN_USER_LIST_FAILURE = "ADMIN_USER_LIST_FAILURE";
export const ADMIN_PROJECT_LIST = "ADMIN_PROJECT_LIST";
export const ADMIN_PROJECT_LIST_SUCCESS = "ADMIN_PROJECT_LIST_SUCCESS";
export const ADMIN_SET_CURRENT_PROJECT = "ADMIN_SET_CURRENT_PROJECT";
export const SET_USER_ADMIN_DATA = "SET_USER_ADMIN_DATA";
export const ADMIN_SET_USER_FIELD = "ADMIN_SET_USER_FIELD";
export const ADMIN_ADD_NEW_USER = "ADMIN_ADD_NEW_USER";
export const ADMIN_SET_PROJECT_FIELD = "ADMIN_SET_PROJECT_FIELD";
export const ADMIN_UPDATE_SURVEY = "ADMIN_UPDATE_SURVEY";
export const ADMIN_ADD_SURVEY = "ADMIN_ADD_SURVEY";
export const ADMIN_ACTIVE_PROJECT_REQUEST = "ADMIN_ACTIVE_PROJECT_REQUEST";
export const ADMIN_AO_QUESTION_LIST = "ADMIN_AO_QUESTION_LIST";
export const ADMIN_AO_QUESTION_LIST_SUCCESS = "ADMIN_AO_QUESTION_LIST_SUCCESS";
export const ADMIN_AM_QUESTION_LIST = "ADMIN_AM_QUESTION_LIST";
export const ADMIN_AM_QUESTION_LIST_SUCCESS = "ADMIN_AM_QUESTION_LIST_SUCCESS";
export const ADMIN_SET_QUESTION_LIST = "ADMIN_SET_QUESTION_LIST"
export const ADMIN_SET_QUESTION_LIST_BY_FIELD = "ADMIN_SET_QUESTION_LIST_BY_FIELD"
export const ADMIN_REPORT_ACCESS_LIST = "ADMIN_REPORT_ACCESS_LIST";
export const ADMIN_REPORT_ACCESS_LIST_SUCCESS = "ADMIN_REPORT_ACCESS_LIST_SUCCESS";
export const ADMIN_SURVEY_SETUP = "ADMIN_SURVEY_SETUP";
export const ADMIN_SURVEY_SETUP_SUCCESS = "ADMIN_SURVEY_SETUP_SUCCESS";
export const ADMIN_SURVEY_CONFIGURATION = "ADMIN_SURVEY_CONFIGURATION";
export const ADMIN_SURVEY_CONFIGURATION_SUCCESS = "ADMIN_SURVEY_CONFIGURATION_SUCCESS";
export const ADMIN_SEND_BULK_INVITATION = "ADMIN_SEND_BULK_INVITATION";
export const ADMIN_BULK_ARCHIVE_USER = "ADMIN_BULK_ARCHIVE_USER";
export const ADMIN_SET_USER_LIST = "ADMIN_SET_USER_LIST";
export const ADMIN_SET_QUESTION_LIST_BLANK = "ADMIN_SET_QUESTION_LIST_BLANK";
export const ADMIN_DELETE_QUESTION = "ADMIN_DELETE_QUESTION";
export const ADMIN_DELETE_QUESTION_SUCCESS = "ADMIN_DELETE_QUESTION_SUCCESS";
export const DEL_MORE_INFO_PAGE = "DEL_MORE_INFO_PAGE";
export const ADMIN_GET_DRIVER_LIST = "ADMIN_GET_DRIVER_LIST";
export const ADMIN_DRIVER_LIST_SUCCESS = "ADMIN_DRIVER_LIST_SUCCESS";
export const ADMIN_UPLOAD_IMAGES = "ADMIN_UPLOAD_IMAGES";
export const IS_FLAGGED = "IS_FLAGGED";
export const FLAGGED_RESPONSE_LIST = "FLAGGED_RESPONSE_LIST";
export const SET_VISIBLE = "SET_VISIBLE";